### PR TITLE
Fixes in options and id + removed unused debug files.

### PR DESCRIPTION
**Pull request by rochacbruno**
- product.id property fixed
- commented out unused writing of debug json files 
- options should have no underline to be serialized
- added example script

### CODE REVIEW

**Comment by ziplokk1** [comment]
Thanks for your contribution! 

I have a question though about why you've changed the BaseParser.id property to return `self._dict.get('product', {}).get('id')`? 

Looking at `/admin/products.json?published_status=any&limit=1&page=1`, I am not seeing a `product` key anywhere in the response body. Can you show an example of the response body that contains that key?

Thank you,
Mark

**Comment by rochacbruno** [comment]
@ziplokk1 that key is returned in the POST when we create a new product, then in apiwrapper the Product instance is created using the json.loads of the that response having "product" key.

I updated the code to handle both cases.

But maybe the change may be in `return Product(json.loads(response.content))` to `return Product(json.loads(response.content.get('product')))` 

as you can see in https://help.shopify.com/api/reference/product#create

```json
HTTP/1.1 201 Created
{
  "product": {
    "id": 1071559576,
    "title": "Burton Custom Freestyle 151",
    "body_html": "<strong>Good snowboard!<\/strong>",
    "vendor": "Burton",
    "product_type": "Snowboard",
    "created_at": "2016-11-15T12:47:00-05:00",
    "handle": "burton-custom-freestyle-151",
    "updated_at": "2016-11-15T12:47:00-05:00",
    "published_at": "2016-11
```

**Comment by ziplokk1** [comment]
Perfect, thank you. Merging now.

**Comment by rochacbruno** [comment]
@ziplokk1 I think it is better to get the proper key in create method, I am sending a new PR with that change.

**Comment by ziplokk1** [comment]
@rochacbruno Yes, you are right. I merged before I saw your comment.

**Pull request merged**
